типо такого: name: Build iOS dylib

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile to dylib (arm64 iOS)
        run: |
          xcrun -sdk iphoneos clang -arch arm64 -dynamiclib -framework Foundation -framework UIKit -o mylib.dylib main.m

      - name: Upload built dylib
        uses: actions/upload-artifact@v4
        with:
          name: Tweak
          path: Tweak.dylib
